server: 
  port: 8761
  servlet:
    context-path: /
#health path
management:
  endpoints:
    web:
      base-path: /
eureka:
  instance:
    hostname: localhost
#    preferIpAddress:
#    status-page-url-path: http://${eureka.instance.hostname}/info
#    health-check-url: http://${eureka.instance.hostname}/health
#    home-page-url: http://${eureka.instance.hostname}
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
  client:
#    healthcheck:
#      enabled: true
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
